# Generated by Django 4.2.3 on 2023-08-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_centre_centreid_remove_elder_elderid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elder',
            name='distancekm',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='elder',
            name='fromtopostal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='elder',
            name='min',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='elder',
            name='minn',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='elder',
            name='rowid',
            field=models.CharField(max_length=255),
        ),
    ]
