# Generated by Django 4.2.3 on 2023-08-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_elder_distancekm_alter_elder_fromtopostal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapTripData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_n', models.CharField(max_length=100)),
                ('to_from_centre_i', models.CharField(max_length=100)),
                ('week_day', models.CharField(max_length=100)),
                ('time_range', models.CharField(max_length=100)),
                ('Trip_Start_Time', models.CharField(max_length=100)),
                ('Trip_End_Time', models.CharField(max_length=100)),
                ('vehicle_plate', models.CharField(max_length=100)),
                ('duration_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('svc_type', models.CharField(max_length=100)),
                ('nric_fin', models.CharField(max_length=100)),
                ('name_surname', models.CharField(max_length=100)),
                ('trans_cap_sub_type_n', models.CharField(max_length=100)),
                ('client_seq_n', models.IntegerField()),
                ('client_postal_code', models.CharField(max_length=100)),
                ('centr_postal_code', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('Trip_ID', models.IntegerField()),
                ('Loading_Time', models.CharField(max_length=100)),
                ('FromToPostal', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=3, max_digits=10)),
                ('min_n', models.DecimalField(decimal_places=5, max_digits=10)),
                ('min_plus_svc_time', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Caregiver', models.CharField(max_length=100)),
                ('Pick_up_Time_Format', models.CharField(max_length=100)),
                ('Pick_up_Time_Delivery', models.CharField(max_length=100)),
                ('IH_OS', models.CharField(max_length=100)),
                ('Cluster', models.CharField(max_length=100)),
            ],
        ),
    ]
